---
name: CI

on:
  # push:
  #   branches: [main]
  #   paths-ignore:
  #     - '**.md'
  #     - 'docs/**'
  #     - '.gitignore'
  #     - 'LICENSE'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  call-ci:
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    uses: riccione/github-workflows/.github/workflows/python-ci.yml@628b13e094babbaa3481b28b390e1cbd86673a3d
    # Optional input override:
    # with:
    #   python-version: "3.11"
